version: 2

updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 7
    ignore:
      - dependency-name: '@angular/cli'
        versions:
          - 11.1.2
          - 11.1.3
          - 11.1.4
          - 11.2.0
          - 11.2.1
          - 11.2.10
          - 11.2.2
          - 11.2.3
          - 11.2.4
          - 11.2.5
          - 11.2.6
          - 11.2.7
          - 11.2.8
          - 11.2.9
      - dependency-name: cypress
        versions:
          - 6.3.0
          - 6.4.0
          - 6.5.0
          - 6.6.0
          - 6.7.0
          - 6.7.1
          - 6.8.0
          - 7.0.0
          - 7.0.1
          - 7.1.0
      - dependency-name: '@angular/core'
        versions:
          - 11.2.1
          - 11.2.11
      - dependency-name: '@angular/compiler-cli'
        versions:
          - 11.2.11
      - dependency-name: '@angular/compiler'
        versions:
          - 11.2.7
      - dependency-name: '@angular/elements'
        versions:
          - 11.2.3
